name: Bencmarks Mac
on:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  benchmark-macos:
    name: Benchmark macos
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Run benchmark
        run: ctest -R MagnetronBenchmark

      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
